FROM node:22-alpine AS development

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME/bin:$PATH"
RUN corepack enable

USER node
WORKDIR /usr/src/frontend

COPY package*.json pnpm*.yaml* ./

RUN pnpm install --frozen-lockfile

COPY . .

CMD ["pnpm", "dev", "---", "--host"]
